[[keymaps]]
command = "None"          # was: SelectNextOrScrollDown
key_sequence = "j"

[[keymaps]]
command = "None"          # was: SelectPreviousOrScrollUp
key_sequence = "k"

[[keymaps]]
command = "None"          # was: SelectNextOrScrollDown
key_sequence = "C-n"

[[keymaps]]
command = "None"          # was: SelectPreviousOrScrollUp
key_sequence = "C-p"

[[keymaps]]
command = "None"          # was: SwitchTheme
key_sequence = "T"
